apiVersion: backstage.io/v1
kind: Component
metadata:
  name: software-templates-java
  description: Teste Java Componente
  tags:
    - java
    - service
spec:
  type: service
  lifecycle: production
  owner: scaribei
